# Generated by Django 5.2 on 2025-04-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
